# Generated by Django 5.1.5 on 2025-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200, unique=True)),
                ('task_description', models.TextField()),
                ('task_image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='')),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('task_deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
