# Generated by Django 5.1.5 on 2025-02-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
    ]
