# Generated by Django 5.1.5 on 2025-02-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_in_trash',
            field=models.BooleanField(default=False),
        ),
    ]
