# Generated by Django 5.1.5 on 2025-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_task_is_in_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('overdue', 'Overdue')], default='pending', max_length=50),
        ),
    ]
