# Generated by Django 5.1.5 on 2025-03-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_name', models.CharField(max_length=200)),
                ('vision_year', models.DateTimeField(auto_now_add=True)),
                ('vision_image', models.ImageField(default='placeholder.png', upload_to='')),
                ('vision_quote', models.TextField(blank=True, null=True)),
                ('is_in_trash', models.BooleanField(default=False)),
            ],
        ),
    ]
